name = "Bafwiz"
author = "Regular Baf"
version = "0.6.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "949a467ab4b8552b790e280447269050d3b564f2a1b5dc4fd807d1cce83e0f25"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
