name = "Mouse Wheelie"
filename = "mousewheelie-1.8.4+mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/u5Ic2U1u/versions/1.8.4+mc1.18.2/mousewheelie-1.8.4%2Bmc1.18.2.jar"
hash-format = "sha1"
hash = "4c86ab249039d13ec1e534d074485377e7d985c0"

[update]
[update.modrinth]
mod-id = "u5Ic2U1u"
version = "nmB6cDYk"
