name = "Universal Graves"
filename = "graves-2.0.0-rc.5+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yn9u3ypm/versions/2.0.0-rc.5+1.18.2/graves-2.0.0-rc.5+1.18.2.jar"
hash-format = "sha1"
hash = "98b024a6c146d46c5faaa88b28a81c75a2f218b0"

[update]
[update.modrinth]
mod-id = "yn9u3ypm"
version = "mz4dvnJd"
